<div class="wrap">
    <div class="icon32" id="icon-options-general"><br /></div>
    <h2>AssetsMinify's configuration</h2>
    <p>&nbsp;</p>
    <form method="post" action="options.php">
        <table class="form-table">
            <tbody>
                <tr valign="top">
                    <th scope="row">
                        <label for="am_use_compass">Use Compass</label>
                    </th>
                    <td>
                        <input name="am_use_compass" type="checkbox" id="am_use_compass" value="1">
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">
                        <label for="am_compass_path">Compass compiler's path</label>
                    </th>
                    <td>
                        <input name="am_compass_path" type="text" id="am_compass_path" value="" class="regular-text">
                    </td>
                </tr>
            </tbody>
        </table>
        <p class="submit">
            <input type="submit" name="submit" id="submit" class="button button-primary" value="Save">
        </p>
    </form>
</div>
